# Codacy configuration for Cookbook TanStack project
# Configured for PostgreSQL 16 - SQL Server patterns are disabled

exclude_patterns:
  - docs/**
  - build/**
  - dist/**
  - .next/**
  - node_modules/**
  - .codacy/**

# Exclude SQL migration files from SQL Server-specific analysis
exclude_paths:
  - drizzle/**

# Pattern exclusions: disable SQL Server T-SQL specific checks
# These patterns do not apply to PostgreSQL 16
exclude:
  # SQL Server: "table must use data compression" - PostgreSQL doesn't have this feature
  - pattern: .*[Tt]able.*[Cc]ompression.*
  # SQL Server: "must set QUOTED_IDENTIFIER" - PostgreSQL specific quoting is different
  - pattern: .*[Qq]uoted.*[Ii]dentifier.*

engines:
  # Enable code quality tools for the project
  eslint:
    enabled: true
  pylint:
    enabled: true
  trivy:
    enabled: true
  semgrep:
    enabled: true

# Coverage-specific exclusions — separate from static-analysis exclude_patterns.
# Without this section, Codacy counts node_modules as coverable lines when
# computing coverage variation, inflating the denominator (e.g. +92k lines
# after installing @testcontainers/postgresql).
coverage:
  exclude_paths:
    - node_modules/**
    - .vinxi/**
    - .output/**
    - public/assets/**
    - drizzle/**
    - playwright-report/**
    - test-results/**
    # Routes are tested via Playwright E2E — exclude from unit-test coverage metric.
    - src/routes/**
    # Seed scripts and type-only files contain no testable logic.
    - src/db/seeds/**
    - src/types/**
    # Test fixture / mock data.
    - src/test-helpers/mocks.ts
